
//Postman API----Post, Get, Put, Delete, Patch methods

//@Postmapping---for RequestBody
POST http://localhost:8080/students/action/insert1
{
    "studentID":101,
    "firstName": "Kamal",
    "lastName": "Saru",
    "phoneNumber": 4434491214,
    "email": "kamal@gmail.com",
    "address": "Baltimore MD",
    "gender": "Male",
    "status": "Active"
}

//----------------------------------------------------------------------------------------
@Postmapping---for RequestParam
Post http://localhost:8080/students/action/insert
studentID:102
firstName:Tanisha
lastName:Thapa
phoneNumber:4434491223
email:tanisha@gmail.com
address:Baltimore MD
gender:Female
status:Active





